instance_groups:
- &logsearch-ingestor-config
  name: ingestor_logsearch_1
  instances: 1
  jobs:
  - name: bpm
    release: bpm
  - name: opensearch
    release: opensearch
    consumes:
      opensearch:
        from: opensearch_manager
        ip_addresses: true
    properties:
      opensearch:
        heap_size: 1G
        http_host: 127.0.0.1
        jvm_options:
        - -Dlog4j2.formatMsgNoLookups=true
  - name: ingestor_logsearch
    consumes:
      opensearch:
        from: opensearch_manager
        ip_addresses: true
    properties:
      logstash:
        jvm_options:
        - -Dlog4j2.formatMsgNoLookups=true
        queue:
          max_bytes: 40gb
      logstash_ingestor:
        syslog_tls:
          port: 6972
          ssl_cert: ((ingestor_syslog_server_tls.certificate))
          ssl_key: ((ingestor_syslog_server_tls.private_key))
      logstash_parser:
        inputs:
        - plugin: s3
          options:
            bucket: (( grab terraform_outputs.logsearch_archive_bucket_name ))
            region: (( grab terraform_outputs.vpc_region ))
            type: syslog
        deployment_dictionary:
        - /var/vcap/jobs/deployment_lookup_config/config/deployment_lookup.yml
        filters:
        - logs-for-cf: /var/vcap/packages/logsearch-filters/logstash-filters-default.conf
        opensearch:
          data_hosts:
          - localhost
          index: "logs-app-%{+YYYY.MM.dd}"
          index_type: '%{@type}'
          ssl:
            ca: ((opensearch_node.ca))
            certificate: ((logstash.certificate))
            private_key: ((logstash.private_key))
    provides:
      ingestor:
        as: ingestor_logsearch_link
    release: opensearch
  - name: deployment_lookup_config
    release: opensearch
  vm_type: r6i.xlarge.logsearch.ingestor
  networks:
  - name: services
  persistent_disk_type: logs_opensearch_ingestor
  stemcell: default
  azs:
  - z1
  vm_extensions:
  - logs-opensearch-ingestor-profile

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_2
  instances: 0

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_3
  instances: 0

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_4
  instances: 0

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_5
  instances: 0

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_6
  instances: 0

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_7

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_8

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_9

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_10

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_11
  instances: 0

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_12

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_13

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_14

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_15
  instances: 0

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_16
  instances: 0

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_17
  instances: 0

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_18
  instances: 0

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_19
  instances: 0

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_20
  instances: 0

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_21
  instances: 0

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_22
  instances: 0

- <<: *logsearch-ingestor-config
  name: ingestor_logsearch_23
  instances: 0
